### ISSUE TITLE
defaults in nvim

### ISSUE THREAD

**Issue by goavn** [deomitrus/dotfiles#10]
colorscheme galben
set noswapfile
set expandtab
set cursorline
set lazyredraw
set splitbelow
set splitright
set hidden
set noruler
set noshowmode
set statusline=
set laststatus=0
set tabstop=2
set softtabstop=2
set shiftwidth=2
set clipboard=unnamed
set fillchars=vert:│,stl:-,stlnc:-
set diffopt+=vertical
set ttimeoutlen=10
set shortmess+=Ic
set inccommand=nosplit

**Comment by deomitrus** [comment]
thanks bruh
